version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
  api:
    build:
      context: .
    restart: always
    links:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - NODE_ENV=dev

volumes:
  db_data: